[s3]
# URL of the target csv file to be uploaded:
s3_url="https://de-materials-tpcds.s3.ca-central-1.amazonaws.com/inventory.csv"

[download]
# download the file into this folder in lambda ephemeral storage:
destination_folder = "/tmp"
# download the file with this filename:
filename = "inventory.csv"

[snowflake]
# snowflake database that the file will be uploaded to:
warehouse = 'TPCDS'
database = 'TPCDS2'
schema = 'raw'
role = 'accountadmin'
file_format = 'comma_csv'
stage_name = 'inventory_stage'
table = 'inventory'