-- FOUR TYPES OF TESTS:
-- 1. NULL TEST
-- 2. UNIQUENESS TEST
-- 3. RELATIONSHIP TEST
-- 4. ACCEPTED VALUE TEST

-- CUSTOMER DIM TESTS
-- NULL TEST: TEST TO CHECK ALL C_CUSTOMER_SK IS NOT NULL. 
SELECT COUNT(*) = 0 FROM SF_TPCDS2.ANALYTICS.CUSTOMER_DIM
WHERE C_CUSTOMER_SK IS NULL;

-- WEEKLY SALES INVENTORY
-- UNIQUENESS TEST: TEST TO CHECK EACH WAREHOUSE_SK, ITEM_SK, SOLD_WK_SK ROW IS UNIQUE
SELECT COUNT(*) = 0 FROM
    (SELECT
        WAREHOUSE_SK,
        ITEM_SK,
        SOLD_WK_SK
    FROM SF_TPCDS2.ANALYTICS.WEEKLY_SALES_INVENTORY
    GROUP BY 1, 2, 3
    HAVING COUNT(*) > 1
    );

-- RELATIONSHIP TEST: TEST TO ENSURE ALL SURROGATE KEYS IN FACT TABLE HAVE AN ASSOCIATE SURROGATE KEY IN THE DIMENSION TABLE
SELECT COUNT(*) = 0 FROM
    (
    SELECT DIM.I_ITEM_SK
    FROM SF_TPCDS2.ANALYTICS.WEEKLY_SALES_INVENTORY FACT
    LEFT JOIN TPCDS2.RAW.ITEM DIM
    ON DIM.I_ITEM_SK = FACT.ITEM_SK
    WHERE DIM.I_ITEM_SK IS NULL
    );

